<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cfgs [

<!ELEMENT cfgs (modulo+)>
<!ATTLIST cfgs nombre CDATA #REQUIRED>

<!ELEMENT modulo (nombre, descripcion, codigo, profesor, fechas)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>

<!ELEMENT fechas (inicio, fin)>

<!ELEMENT inicio (dia, mes, anio)>
<!ELEMENT fin (dia, mes, anio)>

<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

]>

<cfgs nombre="Desarrollo de Aplicaciones Web">

    <modulo>
        <nombre>Bases de Datos</nombre>
        <descripcion>Diseño y gestión de bases de datos relacionales.</descripcion>
        <codigo>0484</codigo>
        <profesor>Juan Pérez</profesor>
        <fechas>
            <inicio>
                <dia>15</dia>
                <mes>09</mes>
                <anio>2025</anio>
            </inicio>
            <fin>
                <dia>20</dia>
                <mes>06</mes>
                <anio>2026</anio>
            </fin>
        </fechas>
    </modulo>

</cfgs>
