<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE test [

<!ELEMENT test (question+)>
<!ELEMENT question (wording,image,choices)>
<!ELEMENT wording (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT choices (choice+)>
<!ELEMENT choice (#PCDATA)>

<!ATTLIST question id CDATA #REQUIRED>
<!ATTLIST choice correct (yes|no) "no">

]>

<test>

   
<question id="1">
        <wording>¿Cuál es el nombre real de Iron Man?</wording>
        <image>images/IronMan.jpg</image>
        <choices>
            <choice>Steve Rogers </choice>
            <choice  correct="yes">Tony Stark</choice>
            <choice>Peter Quill</choice>
            <choice>Charles Xavier</choice>
        </choices>
    </question>

    <question id="2">
        <wording>¿Quién creó originalmente a los Centinelas?</wording>
        <image>images/Centinela.jpg</image>
        <choices>
            <choice>Industrias Stark, bajo un contrato secreto con el gobierno de los Estados Unidos que Tony Stark canceló al enterarse</choice>
            <choice correct="yes">Bolivar Trask, un antropólogo que temía que la evolución mutante extinguiera a la raza humana</choice>
            <choice>Mr Siniestro, como una herramienta para capturar mutantes y experimentar con su ADN</choice>
            <choice>El coronel William Stryker, utilizando tecnología alienígena recuperada</choice>
        </choices>
    </question>
.
    <question id="3">
        <wording>¿Cómo se llama la inteligencia artificial creada por Tony Stark que con el tiempo se convertiría en Visión?</wording>
        <image>images/IA.jpg</image>
        <choices>
            <choice>F.R.I.D.A.Y.</choice>
            <choice>K.A.R.E.N.</choice>
            <choice correct="yes">J.A.R.V.I.S.</choice>
            <choice>E.D.I.T.H.</choice>
        </choices>
    </question>

    <question id="4">
        <wording>¿Cuál es la identidad secreta de Spider-Man?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Peter Parker</choice>
            <choice>Miles Morales</choice>
            <choice>Ned Leeds</choice>
            <choice>Gwen Stacy</choice>
        </choices>
    </question>

    <question id="5">
        <wording>¿Qué gema del infinito está incrustada en la frente de Visión?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Gema de la Mente</choice>
            <choice>Gema del Espacio</choice>
            <choice>Gema del Poder</choice>
            <choice>Gema del Tiempo</choice>
        </choices>
    </question>

    <question id="6">
        <wording>¿Quién es el titán loco que busca recolectar las seis Gemas del Infinito?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Thanos</choice>
            <choice>Darkseid</choice>
            <choice>Ronan</choice>
            <choice>Ego</choice>
        </choices>
    </question>

    <question id="7">
        <wording>¿Cómo obtuvo Lobezno su esqueleto de Adamantium?</wording>
        <image>images/Lobezno.jpg</image>
        <choices>
            <choice>Se ofreció como voluntario en el proyecto canadiense "Arma X" para obtener el poder necesario para vengarse de Dientes de Sable</choice>
            <choice>Nació con él de forma natural debido a una mutación secundaria que se activó durante su adolescencia</choice>
            <choice>Apocalipsis lo capturó y se lo implantó quirúrgicamente como recompensa al convertirlo en su Jinete de la Muerte</choice>
            <choice correct="yes">Fue secuestrado, drogado y sometido a un experimento científico forzoso por el programa militar "Arma X", ya que su factor de curación era el único capaz de sobrevivir al proceso</choice>
        </choices>
    </question>

    <question id="8">
        <wording>¿Cuál es el nombre de la nación gobernada por Victor Von Doom?</wording>
        <image>images/Latveria.jpg</image>
        <choices>
            <choice>Atlantis</choice>
            <choice>Krakoa</choice>
            <choice>Wakanda</choice>
            <choice correct="yes">Latveria</choice>
        </choices>
    </question>

    <question id="9">
        <wording>¿Quiénes son los padres biológicos de Rondador Nocturno?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Mística y el demonio Azazel</choice>
            <choice>Mística y Destino</choice>
            <choice>Charles Xavier y una mutante refugiada de Genosha</choice>
            <choice>Dos artistas de circo alemanes que lo abandonaron al ver su aspecto físico</choice>
        </choices>
    </question>

    <question id="10">
        <wording>¿Quién es el director original de S.H.I.E.L.D. que reúne a los Vengadores?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Nick Furia</choice>
            <choice>Phil Coulson</choice>
            <choice>Maria Hill</choice>
            <choice>Alexander Pierce</choice>
        </choices>
    </question>

    <question id="11">
        <wording>¿Cómo quedó en silla de ruedas el profesor Charles Xavier?</wording>
        <image></image>
        <choices>
            <choice>Quedó paralizado tras un colapso nervioso y físico extremo al intentar conectar su mente con todos los mutantes del planeta a la vez usando un prototipo defectuoso de Cerebro</choice>
            <choice correct="yes">Durante una batalla campal en Cuba contra Sebastian Shaw, una bala desviada por su amigo Magneto le impactó accidentalmente en la columna vertebral</choice>
            <choice>Un alienígena llamado Lucifer le lanzó una enorme roca que aplastó sus piernas en una cueva de los Himalayas, después de que Xavier frustrara sus planes de invasión</choice>
            <choice>Sufrió un atentado con coche bomba perpetrado por un grupo extremista anti-mutante a las puertas de su mansión en Westchester, Nueva York</choice>
        </choices>
    </question>

    <question id="12">
        <wording>¿Cuál es el nombre del mapache antropomórfico que es miembro de los Guardianes de la Galaxia?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Rocket</choice>
            <choice>Groot</choice>
            <choice>Quill</choice>
            <choice>Drax</choice>
        </choices>
    </question>

    <question id="13">
        <wording>¿Qué sustancia transformó a Bruce Banner en Hulk?</wording>
        <image>images/Hulk.jpg</image>
        <choices>
            <choice>El Suero del Súper Soldado</choice>
            <choice correct="yes">Radiación Gamma</choice>
            <choice>Una picadura de araña</choice>
            <choice>Un rayo cósmico</choice>
        </choices>
    </question>

    <question id="14">
        <wording>¿Cómo se llama la mística ciudad oculta donde entrena el Doctor Strange?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Kamar-Taj</choice>
            <choice>K'un-Lun</choice>
            <choice>Ta Lo</choice>
            <choice>Attilan</choice>
        </choices>
    </question>

    <question id="15">
        <wording>¿Quién es el padre biológico de Star-Lord?</wording>
        <image>images/Ego.jpg</image>
        <choices>
            <choice>Yondu Udonta</choice>
            <choice>Thanos</choice>
            <choice correct="yes">Ego el Planeta Viviente</choice>
            <choice>Odin</choice>
        </choices>
    </question>

    <question id="16">
        <wording>¿Cuál es el nombre de la organización terrorista enemiga del Capitán América cuyo lema es "Corta una cabeza y surgirán dos más"?</wording>
        <image>images/Hydra.jpg</image>
        <choices>
            <choice correct="yes">Hydra</choice>
            <choice>A.I.M.</choice>
            <choice>El Clan de los Diez Anillos</choice>
            <choice>La Mano</choice>
        </choices>
    </question>

    <question id="17">
        <wording>¿Qué superheroína es conocida como la Bruja Escarlata?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Wanda Maximoff</choice>
            <choice>Natasha Romanoff</choice>
            <choice>Carol Danvers</choice>
            <choice>Jean Grey</choice>
        </choices>
    </question>

    <question id="18">
        <wording>¿Qué miembro de los 4 Fantásticos murió cerrando el portal de la Zona Negativa?</wording>
        <image></image>
        <choices>
            <choice>Mr Fantástico, Reed Richards</choice>
            <choice>La mujer invisible, Sue Storm</choice>
            <choice correct="yes">La antorcha humana, Jhonny Storm</choice>
            <choice>La cosa, Ben Grim</choice>
        </choices>
    </question>

    <question id="19">
        <wording>¿Cuál es el nombre real de Falcon, quien más tarde asume el manto del Capitán América?</wording>
        <image></image>
        <choices>
            <choice correct="yes">Sam Wilson</choice>
            <choice>Bucky Barnes</choice>
            <choice>Rhodey Rhodes</choice>
            <choice>Clint Barton</choice>
        </choices>
    </question>

    <question id="20">
        <wording>¿Qué villano de Spiderman participó de forma involuntaria en la muerte del Tío Ben?</wording>
        <image></image>
        <choices>
            <choice>Venom</choice>
            <choice correct="yes">El Hombre de Arena</choice>
            <choice>El Lagarto</choice>
            <choice>Dr Octopus</choice>
        </choices>
    </question>

</test>
