=== JosemaMR/LLMM/TEMA5/EJERCICIO 2/alumnos.dtd
<!ELEMENT alumnos (alumno+)>

<!ELEMENT alumno (
    nombre,
    apellidos,
    domicilio,
    telefono+,
    equipo_futbol?,
    aficion*,
    (provincia | pais),
    comentarios?,
    altura?,
    (evaluacion, calificacion)+
)>

<!ATTLIST alumno
    num_alumno ID #REQUIRED
    sexo (hombre | mujer) #IMPLIED
    ayudante IDREF #IMPLIED
>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>

<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono
    tipo (propio | padre | madre | tutor) #REQUIRED
>

<!ELEMENT equipo_futbol (#PCDATA)>
<!ELEMENT aficion (#PCDATA)>

<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT comentarios ANY>

<!ELEMENT altura (#PCDATA)>

<!ELEMENT evaluacion (#PCDATA)>
<!ELEMENT calificacion (#PCDATA)>

=== JosemaMR/LLMM/TEMA5/EJERCICIO 2/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "alumnos.dtd">

<alumnos>

    <alumno num_alumno="A001" ayudante="A002" sexo="hombre">
        <nombre>Juan</nombre>
        <apellidos>Pérez García</apellidos>
        <domicilio>Calle Mayor 15</domicilio>

        <telefono tipo="propio">600123456</telefono>
        <telefono tipo="padre">600654321</telefono>

        <equipo_futbol>Séneca FC</equipo_futbol>

        <aficion>Programación</aficion>
        <aficion>Videojuegos</aficion>

        <provincia>Cádiz</provincia>

        <comentarios>
            Alumno responsable.
            <detalle>Participa en actividades extraescolares.</detalle>
        </comentarios>

        <altura>175</altura>

        <evaluacion>1</evaluacion>
        <calificacion>8</calificacion>

        <evaluacion>2</evaluacion>
        <calificacion>9</calificacion>
    </alumno>

    <alumno num_alumno="A002" sexo="mujer">
        <nombre>María</nombre>
        <apellidos>López Ruiz</apellidos>
        <domicilio>Avenida Andalucía 10</domicilio>

        <telefono tipo="propio">611222333</telefono>

        <aficion>Lectura</aficion>

        <pais>Francia</pais>

        <evaluacion>1</evaluacion>
        <calificacion>10</calificacion>
    </alumno>

</alumnos>
